config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "mains#index"

  get '/about', to: 'abouts#index', as: :about

  get '/password', to: 'passwords#edit', as: :password
  patch '/password', to: 'passwords#update', as: :passwords

  get '/sing-up', to: 'registers#new', as: :register
  post '/sing-up', to: 'registers#create', as: :registers

  get '/sing-in', to: 'sessions#new', as: :signin
  post '/sing-in', to: 'sessions#create', as: :signins

  get '/password/reset', to: 'password_resets#new', as: :password_reset
  post '/password/reset', to: 'password_resets#create', as: :password_resets

  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'

  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets


  delete '/logout', to: 'sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum:1, maximum:280}
  validates :publish_at, presence: true

  after_initialize do 
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do 
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published? 
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end




end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets, dependent: :destroy
  belongs_to :user

  validates :username, uniqueness: true

  def client 
      Twitter::REST::Client.new do |config|
        config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
        config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
        config.access_token        = token
        config.access_token_secret = secret
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets
    has_secure_password
    # /\A[^@\s]+@[^@\s]+\z/ : \A means ^(beginning of the line), \z means $(end of the line), \s means \f,\n,\r,\t,\v(white spaces, form feed)
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email" }
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
    def index
        
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user 
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def required_user_logged_in! 
        redirect_to signin_path, alert: "You must login" if Current.user.nil?
    end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

    def index

    end
    
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

    def twitter 
        Rails.logger.info auth

        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        twitter_account.update(
            name: auth.info.name,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret,
        )

        redirect_to twitter_accounts_path, notice: "Success Connect"
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            # send email

            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "we have to send a link to reset your password"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature 
        redirect_to signin_path, notice: "Your token has expored. pleasetry again"

    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to signin_path, notice: "Your password was reset successfully. please sign in"
        else
            render :edit
        end
    end

    private 
        def password_params
            params.require(:user).permit(:password, :password_confirmation)
        end

    
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :required_user_logged_in!

    def edit
    
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else 
            render :edit
        end
    end

    private 
        def password_params
            params.require(:user).permit(:password, :password_confirmation)
        end

    
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Success"
        else 
            render :new
            # render plain: @user.inspect
        end
    end

    private 
        def user_params
            params.require(:user).permit(:email, :password, :password_confirmation)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id

            redirect_to root_path, notice: "Success Login"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
        
    end
    
    def destroy
        if session[:user_id]
            session[:user_id] = nil
            redirect_to root_path, notice: "Loggoed out"
        end
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :required_user_logged_in!
    before_action :set_tweet, only: [:edit, :update, :show, :destory]
    
    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweets = Tweet.new
    end
    
    def create
        @tweets = Current.user.tweets.new(tweet_params)

        if @tweets.save 
            redirect_to tweets_path,notice: "Tweet was scheduled success"
        else
            render :new 
        end

    end

    def edit
    end

    def update
        if @tweet.update(tweet_params)
            
            redirect_to tweets_path,notice: "Tweet was updated success"
        else
            render :edit
        end
    end

    def destroy
        @tweet.destory
        redirect_to tweets_path,notice: "Tweet was unscheduled"

    end
    
    private
    def tweet_params
        params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)

    end

    def set_tweet
        @tweet = Current.user.tweets.find(prams[:id])
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :required_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]

    def index 
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy 
        @twitter_accounts.destroy
        redirect_to twitter_accounts_path, notice: "Successfully disconnected @#{@twitter_account.username}"
    end

    private 

    def set_twitter_account 
        @twitter_accounts = Current.user.twitter_accounts.find(params[:id])

    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/abouts/index.html.erb
<div class="d-flex algin-items-center justify-content-center">
    <h1>About</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rorails</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <%= csrf_meta_tags %> <%= csp_meta_tag %>

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
        <%= javascript_importmap_tags %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
        <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> %>
    </head>

    <body>
        <%= render template: "shared/_navbar" %>
        <div class="container"><%= render template: "shared/_flash" %> <%= yield %></div>
    </body>
</html>

app/views/mains/index.html.erb
<div class="d-flex algin-items-center justify-content-center">
    <h1>Welcome</h1>
</div>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary", data: {turbo: "false"}%>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user,url: password_reset_edit_path(token: params[:token]) do |form| %>
   <% if form.object.errors.any? %>
    <ul>
        <% form.object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li> 
        <% end %>
    </ul>
    <% end %>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.text_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.text_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot you password</h1>

<%= form_with url: password_reset_path do |form| %>
  <%# <input name='_method' type='hidden' value='patch' /> %>

    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "johndoe@gmail.com" %>
    </div>

    <%= form.submit "Reset Password", class: "btn btn-primary" %>
<% end %>

app/views/registers/new.html.erb
<h1>Sing Ups</h1>

<%= form_with model: @user, url: registers_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "johndoe@gmail.com" %>
    </div>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.text_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.text_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Sign up", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4"><%= flash[:notice] %></div>
<% end %> 

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
<ul>
    <% form.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> 
    <% end %>
</ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to "Navbar", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><%= link_to "Tweets", tweets_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            </ul>

             <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if Current.user %>
                    <li class="nav-item">
                        <%= link_to Current.user.email, password_path %>
                    </li>
                    <li class="nav-item">
                        <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign up", register_path, class:"nav-link" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sign in", signin_path, class:"nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
<%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class:"form-control"} %>
        <%= link_to "Connect your Twitter Account", '/auth/twitter', class: "btn btn-primary" %>

    </div>

    <div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :publish_at %>

        <div class="form-control">
        
            <%= form.datetime_select :publish_at %>
        </div>
    </div>

    <%= form.button "Schedule", class: "btn btn-primary" %>

    <% if form.object.persisted? %>
        <%= button_to "Delete", form.object, method: :delete, data: {confirm: "Are you sure:?"}, class: "btn btn-outline-danger" %>
    <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
<% tweet.body %>

<div class="me-4">
<%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
<%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

<% if tweet.published? %>
<%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
<% else %>
   Scheduled for <%= l tweet.publish_at, format: :long %>
   <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>

<% end %>
</div>

</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Tweets</h1>
    <% if Current.user.twitter_accounts.any? %>
        <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
    <% end %>
</div>

<% if Current.user.twitter_accounts.none? %>
    <%= link_to "Connect your Twitter Account", '/auth/twitter', class: "btn btn-primary" %>
<% end %>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">

<h1>Twitter Accounts</h1>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary", data: {turbo: "false"}%>

</div>

<% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex align-item-center mb-4">
        <div class="me-4">
        <%= image_tag twitter_account.image, class: "rounded-circle" %>
        <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
        </div>
    </div>

    <% button_to "Disconnect", twitter_account, method: :delete, data:{confirm: "Are you sure"} %>
<% end %>